name: Node.js CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Enable Corepack (Yarn & pnpm)
        run: corepack enable

      - name: Install dependencies (Faster with pnpm)
        run: pnpm install --frozen-lockfile

      - name: Create environment file
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV }}" > .env

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Restart server with PM2
        run: |
          pm2 stop server || true
          pm2 delete server || true
          pm2 start index.js --name "server"
          pm2 save
          pm2 startup
